
export const UPDATE_DRAFT = 'UPDATE_DRAFT';

export const ADD_ARGUMENT = 'ADD_ARGUMENT'; 

export const DELETE_ARGUMENT = 'DELETE_ARGUMENT'; 

export const CHANGE_ARGUMENT_TYPE = 'CHANGE_ARGUMENT_TYPE';

export const UPDATE_ARGUMENT = 'UPDATE_ARGUMENT'; 